### ISSUE TITLE
Crawler does not respect politeness across all threads

### ISSUE THREAD

**Issue by kfatehi** [Mondego/crawler4py#4]
It sleeps on each thread -- so parallel threads will exceed the politeness setting.

**Comment by rohan-achar** [comment]
I spawn a new thread for each url to be processed. (to a max defined in the config). Each thread is spawned at least at the interval of politeness setting. So each url is requested at interval of politeness setting.

Not seeing the issue with politeness setting.

**Comment by kfatehi** [comment]
@lordnahor Hmm, I could be wrong... but I did just my logs to the prof and she said confirmed my suspicion that politeness is implemented too loosely. You at your lab? I'm downstairs working on a fix that resolves the server IP and uses that to track politeness.

**Comment by john-ko** [comment]
I ran a crude test, start the script, start a stopwatch.
current politeness setting is at 1000ms
after 10s i stopped it .
here is output

```
Timestamp of start: Tue Jan 26 11:47:44 2016
http://www.ics.uci.edu
http://www.ics.uci.edu/about
http://www.ics.uci.edu/about/about_deanmsg.php
http://www.ics.uci.edu/about/about_factsfigures.php
http://www.ics.uci.edu/about/brenhall
http://www.ics.uci.edu/about/visit
http://www.ics.uci.edu/about/equity
http://www.ics.uci.edu/about/about_contact.php
http://www.ics.uci.edu/dept
http://www.ics.uci.edu/faculty/area
http://www.ics.uci.edu/faculty/centers
http://www.ics.uci.edu/faculty/highlights
```

12 per 10seconds

**Comment by rohan-achar** [comment]
When it should be 11 for those 10 secs (Count the first as instant when you start and 10 more each second after). I think it is fine.

**Comment by kfatehi** [comment]
@lordnahor 

``` python
class SampleConfig(Config):
    def __init__(self):
        Config.__init__(self)
        self.PolitenessDelay = 600
        self.MaxQueueSize = 100
```

Tue Jan 26 10:53:48 2016 http://www.ics.uci.edu
Tue Jan 26 10:53:48 2016 http://www.ics.uci.edu/about/about_factsfigures.php
Tue Jan 26 10:53:48 2016 http://www.ics.uci.edu/about/brenhall
Tue Jan 26 10:53:48 2016 http://www.ics.uci.edu/about
Tue Jan 26 10:53:48 2016 http://www.ics.uci.edu/about/visit
Tue Jan 26 10:53:48 2016 http://www.ics.uci.edu/about/about_deanmsg.php
Tue Jan 26 10:53:48 2016 http://www.ics.uci.edu/about/about_contact.php
Tue Jan 26 10:53:48 2016 http://www.ics.uci.edu/about/equity
Tue Jan 26 10:53:49 2016 http://www.ics.uci.edu/dept
Tue Jan 26 10:53:49 2016 http://www.ics.uci.edu/faculty/area
Tue Jan 26 10:53:49 2016 http://www.ics.uci.edu/faculty/centers
Tue Jan 26 10:53:50 2016 http://www.ics.uci.edu/faculty/highlights
Tue Jan 26 10:53:50 2016 http://www.ics.uci.edu/grad/admissions/Prospective_ApplicationProcess.php
Tue Jan 26 10:53:50 2016 http://www.ics.uci.edu/grad/admissions/index
Tue Jan 26 10:53:50 2016 http://www.ics.uci.edu/grad/degrees/index
Tue Jan 26 10:53:50 2016 http://www.ics.uci.edu/grad/degrees/degrees_PhDOverview
Tue Jan 26 10:53:50 2016 http://www.ics.uci.edu/grad/degrees/degrees_MSOverview
Tue Jan 26 10:53:50 2016 http://www.ics.uci.edu/computing/account/new
Tue Jan 26 10:53:50 2016 http://www.ics.uci.edu/grad/forms/index
Tue Jan 26 10:53:50 2016 http://www.ics.uci.edu/grad/courses/index
Tue Jan 26 10:53:50 2016 http://www.ics.uci.edu/grad/funding/index
Tue Jan 26 10:53:50 2016 http://www.ics.uci.edu/grad/policies/index
Tue Jan 26 10:53:51 2016 http://www.ics.uci.edu/grad/resources
Tue Jan 26 10:53:51 2016 http://www.ics.uci.edu/about/visit/index
Tue Jan 26 10:53:51 2016 http://www.ics.uci.edu/grad/index
Tue Jan 26 10:53:51 2016 http://www.ics.uci.edu/ugrad/index
Tue Jan 26 10:53:51 2016 http://www.ics.uci.edu/ugrad
Tue Jan 26 10:53:52 2016 http://www.ics.uci.edu/ugrad/sao/index

```
```

**Comment by rohan-achar** [comment]
hmm. Yes I'll come down.

**Comment by rohan-achar** [comment]
So the bug was that if the politenessdelay was set to <1000 it ignores the delay because 600/1000 is 0 as it is keeping the type as int. The rest of the logic for the politenessdelay was fine
